# Generated by Django 3.0 on 2019-12-20 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_auto_20191220_0913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='payment_address',
            new_name='payment',
        ),
    ]
