# Generated by Django 3.0 on 2019-12-20 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_auto_20191220_1008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='label',
            new_name='label_color',
        ),
        migrations.AddField(
            model_name='item',
            name='label_text',
            field=models.CharField(default='NEW', max_length=20),
            preserve_default=False,
        ),
    ]
