# Generated by Django 3.0 on 2019-12-23 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_coupon_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='being_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='refund_granted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='refund_requested',
            field=models.BooleanField(default=False),
        ),
    ]
