# Generated by Django 3.0 on 2019-12-23 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_auto_20191223_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='ref_code',
            field=models.CharField(default=123, max_length=20),
            preserve_default=False,
        ),
    ]
